base_url = "https://QEStudios.github.io/matwoya"
title = "Matwoya"
description = "Matwoya is a fork of Mabuya, a minimal Zola theme for building light and SEO-ready blogs."
author = "SKM GEEK"

compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
# More syntax highlighting themes: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
smart_punctuation = true

[extra]
author = "SKM GEEK"
copyright = "© 2026"
github = "https://github.com/QEStudios"
timeformat = "%Y-%m-%d"                 # e.g. 2021-06-14

[[extra.menu]]
name = "RSS"
url = "/rss.xml"

[[extra.menu]]
name = "Atom"
url = "/atom.xml"

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a> and <a href="https://github.com/QEStudios/matwoya">Matwoya</a>.'

[[extra.footer.menu]]
name = "Source Code"
url = "https://github.com/QEStudios/matwoya"

[[extra.footer.menu]]
name = "GitHub"
url = "https://github.com/QEStudios"

[[extra.footer.menu]]
name = "Website"
url = "https://skmgeek.com"
