name = "Matwoya"
description = "A fork of Mabuya, a minimal Zola theme for building light and SEO-ready blogs."
license = "MIT"
homepage = "https://github.com/QEStudios/matwoya"
min_version = "0.18.0"
demo = "https://matwoya.vercel.app/"

[author]
name = "SKM GEEK"
homepage = "https://github.com/QEStudios"

[original]
author = "Miguel Pimentel"
homepage = "https://github.com/semanticdata"
repo = "https://github.com/semanticdata/mabuya"
